name: Download and Upload

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Download
      run: |
        echo "MAIN_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        mkdir -p Downloads
        wget --progress=dot:mega -i .github/lists.txt
        mv -v *.apk Downloads

    - name: Upload
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        repo_name: "${{ env.MAIN_TAG }}"
        tag: ${{ github.ref }}
        checksums: sha256
        file: Downloads/*apk
        overwrite: true
        file_glob: true
        prerelease: false
