name: Download and Upload (Revised)

on:
  push:
    branches: "main"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Download
      run: |
        echo "MAIN_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        FENNEC_URL="https://f-droid.org/repo/org.mozilla.fennec_fdroid"
        MULL_URL="https://f-droid.org/repo/us.spotco.fennec_dos"
        #
        FENNEC_64V8A="1132020"
        FENNEC_V7A="1132000"
        MULL_64V8A="21132020"
        MULL_V7A="21130020"
        #
        mkdir -p Downloads
        wget --progress=dot:mega "$FENNEC_URL"_"$FENNEC_64V8A".apk -O fennec.64.v8a.apk
        wget --progress=dot:mega "$FENNEC_URL"_"$FENNEC_V7A".apk -O fennec.v7a.apk
        wget --progress=dot:mega "$MULL_URL"_"$MULL_64V8A".apk -O mull.64.v8a.apk
        wget --progress=dot:mega "$MULL_URL"_"$MULL_V7A".apk -O mull.v7a.apk
        mv -v *.apk Downloads


    - name: Upload
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "Release ${{ env.MAIN_TAG }}"
        tag: ${{ github.ref }}
        file: Downloads/*apk
        overwrite: true
        file_glob: true
        prerelease: false
