name: Download and Upload
on:
  workflow_dispatch:

jobs:
  Start:
    name: Set Up Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Make Download Folder
      run: |
        mkdir -p Download

    - name: Download Packages
      run: |
        wget --progress=dot:mega -i .github/lists.txt
        mv *.apk Download

    - name: Upload Applications
      uses: termux/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "${{ github.run_id }}"
        tag: "${{ env.MAIN_TAG }}"
        checksums: sha256
        file: Download/*
        overwrite: true
        file_glob: true
        prerelease: false

   - name: Download
      run: |
        rm -rf Download
