name: Merge Filter Lists

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main
    
    - name: Download Lists
      run: |
        wget --progress=dot:mega "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt" -O 1.txt
        wget --progress=dot:mega "https://easylist-downloads.adblockplus.org/advblock.txt" -O 2.txt
        wget --progress=dot:mega "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext" -O 3.txt
        wget --progress=dot:mega "https://urlhaus.abuse.ch/downloads/text" -O 4.txt
        wget --progress=dot:mega "https://secure.fanboy.co.nz/fanboy-mobile-notifications.txt" -O 5.txt
        wget --progress=dot:mega "https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt" -O 6.txt
        wget --progress=dot:mega "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt" -O 7.txt

    - name: Merge and Remove Duplicate Lists
      run: |
        cat 1.txt 2.txt 3.txt 4.txt 5.txt 6.txt 7.txt > hard-base.txt
        cat 2.txt 5.txt 6.txt 7.txt > lite-base.txt
        cat 1.txt 2.txt 5.txt 7.txt > unbreak-base.txt
        sort hard-base.txt | uniq > hard.txt && rm -rf hard-base.txt
        sort lite-base.txt | uniq > lite.txt && rm -rf lite-base.txt
        sort unbreak-base.txt | uniq > unbreak.txt && rm -rf unbreak-base.txt
        rm -rf 1.txt 2.txt 3.txt 4.txt 5.txt 6.txt 7.txt
        mkdir -p Downloads && mv *.txt Downloads

    - name: Upload Lists
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "Filter List"
        tag: ${{ github.ref }}
        file: Downloads/*.txt
        overwrite: true
        file_glob: true
        prerelease: false
