name: Download and Upload

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Download
      run: |
        echo "MAIN_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        wget --progress=dot:mega -i .github/lists.txt

    - name: Upload
      uses: termux/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "${{ github.run_id }}"
        tag: "${{ env.MAIN_TAG }}"
        checksums: sha256
        file: *.apk
        overwrite: true
        file_glob: true
        prerelease: false
