name: Downd and Upload (Revised)

on:
  #push:
    #branches: "main"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Download
      run: |
        echo "MAIN_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        chmod +x download.sh && ./download.sh

    - name: Upload
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "Release ${{ env.MAIN_TAG }}"
        tag: ${{ github.ref }}
        file: Downloads/*apk
        overwrite: true
        file_glob: true
        prerelease: false
