name: Download and Upload

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Download
      run: |
        echo "HOMEDIR=$(pwd)" >> $GITHUB_ENV
        echo "MAIN_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        mkdir -p Download
        wget --progress=dot:mega -i .github/lists.txt
        mv *.apk Download

    - name: Upload
      uses: termux/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "Generation"
        tag: "1.0.1"
        checksums: sha256
        file: ${{ env.HOMEDIR }}/org.mozilla.fennec_fdroid_1111000.apk
        overwrite: true
        file_glob: true
        prerelease: false
