name: Test

on:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Download
      run: |
        chmod +x script.sh && ./script.sh

    - name: Upload
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "Release ${{ env.MAIN_TAG }}"
        tag: ${{ github.ref }}
        file: /*apk
        overwrite: true
        file_glob: true
        prerelease: false
